#!/bin/bash

PUBLIC_KEY_FILE=$1

MANAGER_USER=manager
MANAGER_USER_HOME=/home/$MANAGER_USER
MANAGER_USER_SSH_KEY_DIR=$MANAGER_USER_HOME/.ssh
MANAGER_USER_AUTHORIZED_KEY_FILE=$MANAGER_USER_SSH_KEY_DIR/authorized_keys

adduser --disabled-password --gecos ',,,,,' $MANAGER_USER
usermod -aG sudo $MANAGER_USER
mkdir $MANAGER_USER_SSH_KEY_DIR
chmod 700 $MANAGER_USER_SSH_KEY_DIR
touch $MANAGER_USER_AUTHORIZED_KEY_FILE
chmod 600 $MANAGER_USER_AUTHORIZED_KEY_FILE
cat "$PUBLIC_KEY_FILE" >> $MANAGER_USER_AUTHORIZED_KEY_FILE
chown -R $MANAGER_USER $MANAGER_USER_SSH_KEY_DIR
echo "$MANAGER_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$MANAGER_USER
